In [4]:
from tensorflow.keras.layers import SimpleRNN, Dense, Flatten,Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD,Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
N=1 #number of samples
T=10 #sequence length
D=3 #number of input features
K=2 #number of output units
X=np.random.randn(N,T,D)
#M - number of hidden units

In [27]:
#make rnn
M=5
i=Input(shape=(T,D))
l1=SimpleRNN(M)(i)
x=Dense(K)(l1)

model=Model(i,x)

In [28]:
Yhat=model.predict(X)
Yhat

1/1 [==============================] - 0s 261ms/step


array([[-0.40034887,  0.6008744 ]], dtype=float32)

In [29]:
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 5)                 45        
                                                                 
 dense_4 (Dense)             (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.layers[1].get_weights()

[array([[ 0.58495945, -0.29245526,  0.5733678 ,  0.46434504, -0.1777947 ],
        [-0.8578524 ,  0.36114007, -0.10162693, -0.5915611 ,  0.00770426],
        [ 0.54303867,  0.27487355,  0.5974265 , -0.29797536,  0.49735552]],
       dtype=float32),
 array([[-0.1858654 , -0.09420583,  0.5808596 ,  0.4086161 ,  0.67246884],
        [ 0.1913147 ,  0.95368844, -0.04014738,  0.20806634,  0.09472939],
        [ 0.14326677, -0.20220466, -0.75491583,  0.48028162,  0.37150988],
        [-0.89606297,  0.20014086, -0.28536445, -0.22220671,  0.1618829 ],
        [ 0.32465136,  0.02570086, -0.09828287, -0.7139294 ,  0.61203456]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [31]:
#check shapes
#first output is input>hidden
#second output is hidden>hidden
#third is bias term

a,b,c=model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [32]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [33]:
h_last=np.zeros(M) #initial hidden state
x=X[0] #one and only sample
yhats=[] #where the outputs are stored

for t in range(T):
    h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
    y=h.dot(Wo)+bo #only care about this value in last iteration
    yhats.append(y)
    
    #assign h to h_last
    h_last=h

print(yhats[-1])

[-0.40034907  0.60087444]
